/* IMPORTANT INSTRUCTIONS FOR LEARNERS
1) DO NOT CHANGE THE ORDER OF COLUMNS.
2) YOUR QUERY SHOULD DISPLAY COLUMNS IN THE SAME ORDER AS MENTIONED IN ALL QUESTIONS.
3) YOU CAN FIND THE ORDER OF COLUMNS IN QUESTION TEMPLATE SECTION OF EACH QUESTION.
4) USE ALIASING AS MENTIONED IN QUESTION TEMPLATE FOR ALL COLUMNS
5) DO NOT CHANGE COLUMN NAMES*/
                   
-- Question 1 (Marks: 3)
-- Objective: Determine, for flights that actually departed later than scheduled, what the departure delay is (in minutes).
-- Calculate the Delay in Departures for Delayed Flights
-- Question Template: Display following columns flight_id, flight_no, departure_delay_minutes

-- Write your SQL solution here: 
select flight_id,flight_no,timestampdiff(minute,scheduled_departure,actual_departure)
as departure_delay_minutes from flights where actual_departure is not null and scheduled_departure
is not null and timestampdiff(minute,scheduled_departure,actual_departure) !=0;

-- Question 2 (Marks: 3)
-- Objective: Show how frequently each aircraft is used by counting the number of flights operated by each aircraft.
-- List Flights Grouped by Aircraft to See Usage Frequency
-- Question Template: Display following columns aircraft_code, total_flights, avg_flight_duration_minutes

-- Write your SQL solution here:
SELECT 
  aircraft_code,
  COUNT(*) AS total_flights,
  ROUND(AVG(TIMESTAMPDIFF(MINUTE, scheduled_departure, scheduled_arrival)),2) AS avg_flight_duration_minutes
FROM flights
GROUP BY aircraft_code;

-- Question 3 (Marks: 3)
-- Objective: Aggregate the total revenue generated by each flight by summing up the fare amounts from the ticket_flights table.
-- Calculate Total Revenue per Flight from the Ticket_Flights Table
-- Question Template: Display following columns flight_id, flight_no, total_revenue

-- Write your SQL solution here:
select f.flight_id,f.flight_no,sum(tf.amount) as total_revenue
from flights f join ticket_flights tf on f.flight_id = tf.flight_id
group by f.flight_id,f.flight_no
order by total_revenue desc;

-- Question 4 (Marks: 3)
-- Objective: Examine boarding pass data to identify how passengers are being boarded by calculating the average boarding number per flight.
-- Analyze Boarding Numbers per Flight to Detect Patterns in Boarding Pass Allocation
-- Question Template: Display following columns flight_id, avg_boarding_no, total_boarding_passes

-- Write your SQL solution here:
select flight_id,round(avg(boarding_no),2) as avg_boarding_no,count(boarding_no) as total_boarding_passes
from boarding_passes
group by flight_id
order by total_boarding_passes desc;

-- Question 5 (Marks: 3)
-- Objective: Identify seat occupancy by comparing the number of boarding passes (occupied seats) to the total seats available on an aircraft.
-- Determine Occupancy per Aircraft
-- Question Template: Display following columns flight_id, flight_no, aircraft_code, total_seats, occupied_seats, occupancy_rate_percentage

-- Write your SQL solution here:
SELECT 
    f.flight_id,
    f.flight_no,
    f.aircraft_code,
    (SELECT COUNT(*) FROM seats s WHERE s.aircraft_code = f.aircraft_code) AS total_seats,
    COUNT(bp.ticket_no) AS occupied_seats,
    ROUND(COUNT(bp.ticket_no) / (SELECT COUNT(*) FROM seats s WHERE s.aircraft_code = f.aircraft_code) * 100, 2) AS occupancy_rate_percentage
FROM flights f
LEFT JOIN boarding_passes bp ON f.flight_id = bp.flight_id
GROUP BY f.flight_id, f.flight_no, f.aircraft_code;

-- Question 6 (Marks: 3)
-- Objective: Identify the three flights that generated the highest revenue based on ticket sales.
-- Top 3 Flights by Revenue
-- Question Template: Display following columns flight_id, flight_no, total_revenue

-- Write your SQL solution here:
select f.flight_id,f.flight_no,sum(tf.amount) as total_revenue
from flights f inner join ticket_flights tf on f.flight_id = tf.flight_id
group by f.flight_id,f.flight_no
order by total_revenue desc limit 3;

-- Question 7 (Marks: 3)
-- Objective: Determine the average flight duration for each aircraft model, allowing you to see how flight performance might vary between different models.
-- Average Flight Duration by Aircraft Model
-- Question Template: Display following columns model, avg_duration_minutes

-- Write your SQL solution here:
SELECT 
  a.model,
  AVG(TIMESTAMPDIFF(MINUTE, f.scheduled_departure, f.scheduled_arrival)) AS avg_duration_minutes
FROM flights f
JOIN aircrafts a ON f.aircraft_code = a.aircraft_code
GROUP BY a.model;

-- Question 8 (Marks: 3)
-- Objective: Count how many flights depart from each airport to assess airport activity levels.
-- Flight Count per Airport (Departure)
-- Question Template: Display following columns departure_airport, departure_flights

-- Write your SQL solution here:
SELECT 
  departure_airport AS departure_airport, 
  COUNT(*) AS departure_flights
FROM flights
GROUP BY departure_airport;

-- Question 9 (Marks: 3)
-- Objective: Count how many flights depart from and arrive at each airport to assess airport activity levels.
-- Flight Count per Airport (Arrival)
-- Question Template: Display following columns arrival_airport, arrival_flights

-- Write your SQL solution here:
SELECT 
  arrival_airport AS arrival_airport, 
  COUNT(*) AS arrival_flights
FROM flights
GROUP BY arrival_airport;

-- Question 10 (Marks: 3)
-- Objective: Analyze trends in bookings over time by grouping bookings by date, counting total bookings, and summing up the revenue.
-- Daily Booking Trends
-- Question Template: Display following columns booking_date, total_bookings, total_revenue

-- Write your SQL solution here:
select date(book_date) as booking_date,
count(book_ref) as total_bookings,
sum(total_amount) as total_revenue
from bookings
group by date(book_date)
order by booking_date;

-- Question 11 (Marks: 3)
-- Objective: Identify the most common routes by counting the number of flights for each departure–arrival airport pair.
-- Frequent Routes Analysis
-- Question Template: Display following columns departure_airport, arrival_airports, flights_count

-- Write your SQL solution here:
select departure_airport, arrival_airport, count(flight_id)flights_count
from flights
group by departure_airport,arrival_airport
order by flights_count desc;

-- Question 12 (Marks: 3)
-- Objective: Determine how many passengers boarded each flight by counting the boarding passes issued.
-- Passenger Boarding Summary per Flight
-- Question Template: Display following columns flight_id, passengers_boarded

-- Write your SQL solution here:
select flight_id, count(boarding_no) as passengers_boarded
from boarding_passes
group by flight_id
order by passengers_boarded desc;

-- Question 13 (Marks: 3)
-- Objective: Assess the boarding process by calculating the average boarding order number for each flight, which may indicate the boarding strategy or sequence.
-- Average Boarding Number per Flight
-- Question Template: Display following columns flight_id, avg_boarding_no

-- Write your SQL solution here:
select flight_id, round((avg(boarding_no)),2) as avg_boarding_no
from boarding_passes
group by flight_id
order by avg_boarding_no desc;

-- Question 14 (Marks: 3)
-- Objective: Aggregate the total amount spent by each passenger across all their tickets by joining the tickets and ticket_flights tables.
-- Total Spend per Passenger
-- Question Template: Display following columns passenger_id, total_tickets, total_spent

-- Write your SQL solution here:
select t.passenger_id, count(t.ticket_no) as total_tickets, sum(tf.amount) as total_spent
from tickets t inner join ticket_flights tf 
on t.ticket_no = tf.ticket_no
group by t.passenger_id
order by total_spent desc;

-- Question 15 (Marks: 3)
-- Objective: Analyze the distribution of ticket volume and revenue across different fare conditions.
-- Fare?Condition Distribution
-- Question Template: Display following columns fare_conditions, tickets_sold, total_revenue

-- Write your SQL solution here:
select fare_conditions, count(ticket_no) as tickets_sold, sum(amount) as total_revenue
from ticket_flights
group by fare_conditions
order by total_revenue desc;

-- Question 16 (Marks: 3)
-- Objective: Aggregate total revenue generated by each departure?arrival airport route.
-- Revenue by Route
-- Question Template: Display following columns departure_airport, arrival_airport, total_route_revenue

-- Write your SQL solution here:
select f.departure_airport, f.arrival_airport, sum(tf.amount) as total_route_revenue
from flights f inner join ticket_flights tf
on f.flight_id = tf.flight_id
group by f.departure_airport, f.arrival_airport
order by total_route_revenue desc;

-- Question 17 (Marks: 2)
-- Objective: Identify the top 5 booking hours of the day by volume of bookings
-- Peak Booking Hours
-- Question Template: Display following columns booking_hour, bookings_count

-- Write your SQL solution here:
select extract(hour from(book_date)) as booking_hour, count(distinct book_ref) as bookings_count
from bookings
group by extract(hour from(book_date))
order by bookings_count desc limit 5;

